### ISSUE TITLE
Top News Theme: Darken Body Typeface Color

### ISSUE THREAD

**Issue by rveitch** [openfcci/areavoices-network#21]
Add this to the styles of the Top News Child Themes:

```CSS
/* Darken Body Typeface */
#content-area {
    color: #333 !important;
}
```
