### ISSUE TITLE
Create site for Bakken Today

### ISSUE THREAD

**Issue by rveitch** [openfcci/areavoices-network#34]
### Overview
@mberreth 
We need to spin up a site for [Bakken Today](http://www.bakkentoday.com/), probably bakkentoday.areavoices.com. We will use the Top News theme. We will also need to add the targeted JobsHQ widget to this site. The info for that can be found [here](https://docs.google.com/document/d/1wd9uTUW5Xrl9pDPDB0l3sVFaTR7KvLAhbubRjqQ06Ss/edit?ts=56cc8266). 

#### Discovery Checklist
- Determine categories migration
- **Nav** Sections Determined
- Pages Determined
- 'Tools & Features' Determined
- Layout & Design
  - Site Logo
  - Color palette determined
- Article Tagline and [story lines](http://wptavern.com/easily-display-highlights-of-a-story-with-the-story-lines-plugin)
- Expanded Open Author Tagline & Meta support
- Child Theme needed? :question:
- Google Analytics /  Tracking Code :question:
- Content migration? :question:

#### Production Checklist
- [x] Site Setup & Options
  - [x] Create [bakkentoday.areavoices.com](http://bakkentoday.areavoices.com/)
  - [x] Site Title
  - [x] Site Tagline
  - [x] Site Icon Created/Set
  - [x] `Option` Timezone: Chicago
  - [x] Create 'Home' page
    - [x] Page Attributes → Template: `Home`
  - [x] `Option` Front page displays: 'Home'
- [x] Connect Jetpack
- [x] Theme assigned
- [x] Theme Setup
  - [x] Custom CSS
  - [x] Color Palette set in theme colors
  - [x] Footer info set `© 2016 Forum Communications Co. — All rights reserved`
- [x] `FCC Open Byline Authors` plugin activated
- [x] Site Options set & standardized
- [x] Categories created
- [x] Menu(s)/Nav set
  - [x] Main Menu
  - [x] Mobile Menu
- [x] Widgets set
- [x] Social Media set (N/A)
- [x] Activate Nativo Plugin
- [x] Add the targeted JobsHQ widget 

### Reference
- [Basecamp Task](https://basecamp.com/2925531/projects/10913979/todos/236964130)
- http://www.bakkentoday.com/
- [JobsHQ Ad Widgets - Deploy Codes and Business Rules](https://docs.google.com/document/d/1wd9uTUW5Xrl9pDPDB0l3sVFaTR7KvLAhbubRjqQ06Ss/edit?ts=56cc8266)

**Comment by rveitch** [comment]
```css
#foot-top {
  display: none;
}
#foot-copy {
  line-height: 18px;
}
#foot-copy A:hover {
  color: #00aeef;
}

/* Hide Author Card Image on Posts */
.author-img {
  display: none;
}

/* Hide Author Twitter Link */
span.author-twit {
  display: none;
}

/* Hide Author Card Image on Author Page */
.author-page-img {
  Display: none;
}

/* Hide Author Twitter Link on Author Page */
ul.author-social li {
  Display: None;
}
#head-wrap {
  margin-top: 0x;
  padding-top: 0px;
}
```
